//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcSoluciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaServicio()
        {
            this.DetalleServicio = new HashSet<DetalleServicio>();
        }
    
        public int id_factura { get; set; }
        public Nullable<int> id_informe_fallo { get; set; }
        public decimal total_servicio { get; set; }
        public Nullable<decimal> total_repuestos { get; set; }
        public Nullable<decimal> iva { get; set; }
        public decimal total_factura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleServicio> DetalleServicio { get; set; }
        public virtual InformeFallo InformeFallo { get; set; }
    }
}
