//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcSoluciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeFallo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformeFallo()
        {
            this.FacturaServicio = new HashSet<FacturaServicio>();
        }
    
        public int id_informe { get; set; }
        public Nullable<int> id_computadora { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_aprox { get; set; }
        public string repuesto { get; set; }
    
        public virtual Computadora Computadora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaServicio> FacturaServicio { get; set; }
    }
}
