//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcSoluciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerario
    {
        public int id_itinerario { get; set; }
        public Nullable<System.DateTime> fecha_asignacion { get; set; }
        public string descripcion { get; set; }
        public string num_cedulaTec { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
