//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcSoluciones.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stsolucionesPcEntities : DbContext
    {
        public stsolucionesPcEntities()
            : base("name=stsolucionesPcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Computadora> Computadora { get; set; }
        public virtual DbSet<DetalleServicio> DetalleServicio { get; set; }
        public virtual DbSet<FacturaServicio> FacturaServicio { get; set; }
        public virtual DbSet<InformeFallo> InformeFallo { get; set; }
        public virtual DbSet<Itinerario> Itinerario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
